---
- hosts: all
  gather_facts: no

  vars:
      new_luks_password: "{{ luks_password }}"

  tasks:
      - block:
        - import_role:
            name: unlock_luks
        vars:
            luks_password : "temp"
      - name: Gathering facts
        setup:
      - set_fact:
            new_hashed_password : "{{ ansible_become_pass | password_hash('sha512') }}"
      - block:
        - name: Set the user password
          user:
             name: "{{ ansible_user_id }}"
             password: "{{ new_hashed_password }}"
        vars:
            ansible_become_pass: "temp"
        become: true
      - name: Change the luks encryption password
        block:
        - name: generate the new keyfile
          command: bash -c "printf \"{{ luks_password }}\" > newkey"
        - name: generate the old keyfile
          command: bash -c "printf \"temp\" > oldkey"
        - name: "add the new LUKS password"
          luks_device:
            keyfile: oldkey
            device: "/dev/sda5"
            new_keyfile: newkey
          become: true
        - name: "remove the old LUKS password"
          luks_device:
            keyfile: newkey
            device: "/dev/sda5"
            remove_keyfile: oldkey
          become: true
        always:
            - name: overwrite the keyfiles
              command: shred -f oldkey newkey
            - name: remove the keyfiles
              command: rm -f oldkey newkey
